version: '3.4'

services:
  demo-frontend:
    image: nginx
    container_name: demo-frontend
    ports:
      - 8000:80
      - 8080:8080
    volumes:
      - ./nginx-demo-files:/usr/share/nginx/html
    
  demo-backend:
    image: demo-backend:local
    build:
      context: ./demo-backend
      dockerfile: Dockerfile
    hostname: demo-backend
    container_name: demo-backend
    ports:
      - 8888:80
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_DATASOURCE_URL=jdbc:postgresql://demo-database:5432/demo
      - SPRING_DATASOURCE_USERNAME=demo-user
      - SPRING_DATASOURCE_PASSWORD=demo-password
      - SERVER_PORT=80
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQL10Dialect

  demo-database:
    image: postgres:12
    container_name: demo-database
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER="demo-user"
      - POSTGRES_PASSWORD="demo-password"
      - POSTGRES_DB="demo"
      - POSTGRES_HOST_AUTH_METHOD="trust"

  demo-database-frontend:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports: 
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0

    
volumes:
  pgdata:
    driver: local
